import { z } from 'zod'
import type { Entity } from '@/models/entity'

export const EntitySchema = z
  .object({
    id: z.number(), // autogenerated
    title: z.string().min(1, { message: 'Требуется ввести значение' }).max(50), // < 50 symbols
    description: z.string(), // md
    published: z.boolean(), // required
    published_from: z.string().date('Дата введена неверно').nullable(),
  }) satisfies z.ZodType<Entity>

export const CreateEntitySchema = EntitySchema
  .omit({ id: true })
